create table extr_rpsale
(
    "ExciseTaxNbr" text,
    "Major" text,
    "Minor" text,
    "DocumentDate" text,
    "SalePrice" text,
    "RecordingNbr" text,
    "Volume" text,
    "Page" text,
    "PlatNbr" text,
    "PlatType" text,
    "PlatLot" text,
    "PlatBlock" text,
    "SellerName" text,
    "BuyerName" text,
    "PropertyType" text,
    "PrincipalUse" text,
    "SaleInstrument" text,
    "AFForestLand" text,
    "AFCurrentUseLand" text,
    "AFNonProfitUse" text,
    "AFHistoricProperty" text,
    "SaleReason" text,
    "PropertyClass" text,
    "SaleWarning" text
)